name: moba
channels:
  - defaults
dependencies:
  - scipy
  - matplotlib
  - python=3.11
  - pyyaml
  - tqdm
  - ipykernel
  - opencv
  - git
  - conda-forge::albumentations
  - conda-forge::wandb